export { default as LogoAxios } from "../../public/tecs/axios.png";
export { default as LogoDocker } from "../../public/tecs/docker.png";
export { default as LogoCss } from "../../public/tecs/logoCss.svg";
export { default as LogoFigma } from "../../public/tecs/logoFigma.svg";
export { default as LogoFirebase } from "../../public/tecs/logoFirebase.svg";
export { default as LogoGit } from "../../public/tecs/logoGit.svg";
export { default as LogoHtml } from "../../public/tecs/logoHtml.svg";
export { default as LogoJavascript } from "../../public/tecs/logoJavascript.svg";
export { default as LogoNextjs } from "../../public/tecs/logoNextjs.svg";
export { default as LogoReactjs } from "../../public/tecs/logoReactjs.svg";
export { default as LogoSass } from "../../public/tecs/logoSass.svg";
export { default as LogoTailwind } from "../../public/tecs/logoTailwind.svg";
export { default as LogoTs } from "../../public/tecs/logoTs.svg";
export { default as LogoMongoDB } from "../../public/tecs/mongodb.svg";
export { default as LogoPrisma } from "../../public/tecs/prisma (2).png";
export { default as LogoNodejs } from "../../public/tecs/nodejs-icon.svg";
