import { v4 as uuid } from "uuid";
import * as imports from "./imports";

export const techs = [
  {
    id: uuid(),
    type: "image",
    name: "HTML",
    width: 50,
    height: 50,
    delay: 100,
    image: imports.LogoHtml,
  },
  {
    id: uuid(),
    type: "image",
    name: "CSS",
    width: 50,
    height: 50,
    delay: 100,
    image: imports.LogoCss,
  },

  {
    id: uuid(),
    type: "image",
    name: "Tailwind",
    width: 50,
    height: 50,
    delay: 100,
    image: imports.LogoTailwind,
  },

  {
    id: uuid(),
    type: "image",
    name: "JavaScript",
    width: 50,
    height: 50,
    delay: 100,
    image: imports.LogoJavascript,
  },
  {
    id: uuid(),
    type: "image",
    name: "NodeJs",
    width: 50,
    height: 50,
    delay: 100,
    image: imports.LogoNodejs,
  },
  {
    id: uuid(),
    type: "image",
    name: "Typescript",
    width: 50,
    height: 50,
    delay: 100,
    image: imports.LogoTs,
  },
  {
    id: uuid(),
    type: "image",
    name: "React",
    width: 50,
    height: 50,
    delay: 100,
    image: imports.LogoReactjs,
  },
  {
    id: uuid(),
    type: "image",
    name: "NextJs",
    width: 50,
    height: 50,
    delay: 100,
    image: imports.LogoNextjs,
  },

  {
    id: uuid(),
    type: "image",
    name: "FireBase",
    width: 50,
    height: 50,
    delay: 100,
    image: imports.LogoFirebase,
  },
  {
    id: uuid(),
    type: "image",
    name: "MongoDB",
    width: 50,
    height: 50,
    delay: 100,
    image: imports.LogoMongoDB,
  },

  {
    id: uuid(),
    type: "image",
    name: "Prisma",
    width: 50,
    height: 50,
    delay: 100,
    image: imports.LogoPrisma,
  },

  {
    id: uuid(),
    type: "image",
    name: "Axios",
    width: 50,
    height: 50,
    delay: 100,
    image: imports.LogoAxios,
  },
  {
    id: uuid(),
    type: "image",
    name: "Docker",
    width: 50,
    height: 50,
    delay: 100,
    image: imports.LogoDocker,
  },
  {
    id: uuid(),
    type: "image",
    name: "Git",
    width: 50,
    height: 50,
    delay: 100,
    image: imports.LogoGit,
  },
  {
    id: uuid(),
    type: "image",
    name: "Figma",
    width: 50,
    height: 50,
    delay: 100,
    image: imports.LogoFigma,
  },
];
